"""zzzzz

Revision ID: 31e39f7a62fe
Revises: dfcccd197f8a
Create Date: 2023-02-25 01:07:39.656806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e39f7a62fe'
down_revision = 'dfcccd197f8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password_hash', sa.String(), nullable=True))
    op.drop_column('Users', 'password_hashed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password_hashed', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'password_hash')
    # ### end Alembic commands ###
