"""zzz

Revision ID: 48336e91271d
Revises: 999fc3da6f0f
Create Date: 2023-02-24 23:00:06.624880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48336e91271d'
down_revision = '999fc3da6f0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Users_created_by'), 'Users', ['created_by'], unique=False)
    op.create_index(op.f('ix_Users_modified_by'), 'Users', ['modified_by'], unique=False)
    op.create_foreign_key(None, 'Users', 'Users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'Users', 'Users', ['modified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_index(op.f('ix_Users_modified_by'), table_name='Users')
    op.drop_index(op.f('ix_Users_created_by'), table_name='Users')
    # ### end Alembic commands ###
