"""zz

Revision ID: 999fc3da6f0f
Revises: 9462d2eb5c03
Create Date: 2023-02-24 21:44:23.044511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999fc3da6f0f'
down_revision = '9462d2eb5c03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
