"""zzzzz

Revision ID: f489f9801513
Revises: 31e39f7a62fe
Create Date: 2023-02-25 16:13:46.166686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f489f9801513'
down_revision = '31e39f7a62fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
